// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DemoWebApi.Models
{
    public partial class Employee
    {
        [Key]
        public int EmployeeId { get; set; }

        [Required]
        [StringLength(50)]
        public string FirstName { get; set; }

        [Required]
        [StringLength(50)]
        public string LastName { get; set; }

        [Required]
        [StringLength(50)]
        public string Email { get; set; }

        [Required]
        [StringLength(50)]
        public string ContactNumber { get; set; }

        [Column(TypeName = "decimal(18, 0)")]
        public decimal Salary { get; set; }

        [Required]
        [StringLength(50)]
        public string Designation { get; set; }

        public int DepartmentId { get; set; }

        [Column(TypeName = "datetime")]
        public DateTime CreatedAt { get; set; }

        public bool IsDeleated { get; set; }
        public string Password { get; set; }

        public virtual Department Department { get; set; }
    }
}